import {chromium} from "../../games/node_modules/playwright-core/index.mjs";
import {createServer} from "node:http";
import {readFile} from "node:fs/promises";
import {extname,join} from "node:path";
const root=new URL("../",import.meta.url).pathname;
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8"};
const server=createServer(async(req,res)=>{try{const urlPath=new URL(req.url,"http://localhost").pathname;const path=urlPath==="/"?"index.html":urlPath.slice(1);const data=await readFile(join(root,path));res.writeHead(200,{"content-type":types[extname(path)]||"application/octet-stream"});res.end(data)}catch{res.writeHead(404);res.end("not found")}});
await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
const base="http://127.0.0.1:"+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"});
const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1});
const page=await context.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
await page.goto(base,{waitUntil:"networkidle"});await page.locator("#startBtn").tap();await page.waitForTimeout(250);
const before=await page.evaluate(()=>({x:window.__echoRift.game.player.x,y:window.__echoRift.game.player.y}));
const cdp=await context.newCDPSession(page);
await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:90,y:650,id:1,radiusX:4,radiusY:4,force:1}]});
await page.waitForTimeout(80);
const activeDuring=await page.locator("#joystick").evaluate(el=>el.classList.contains("active"));
await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:145,y:600,id:1,radiusX:4,radiusY:4,force:1}]});
await page.waitForTimeout(300);await page.screenshot({path:"qa-touch-mobile.png",fullPage:true});await page.waitForTimeout(300);
await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await page.waitForTimeout(80);
const afterMove=await page.evaluate(()=>({x:window.__echoRift.game.player.x,y:window.__echoRift.game.player.y}));
await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:330,y:540,id:2,radiusX:4,radiusY:4,force:1}]});
await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await page.waitForTimeout(80);
const afterDash=await page.evaluate(()=>({dashT:window.__echoRift.game.player.dashT,dashActive:window.__echoRift.game.player.dashActive}));
const moved=Math.hypot(afterMove.x-before.x,afterMove.y-before.y);
console.log(JSON.stringify({before,afterMove,moved,activeDuring,afterDash,errors},null,2));
await browser.close();await new Promise(resolve=>server.close(resolve));
if(errors.length||!activeDuring||moved<15||afterDash.dashT<=0)process.exit(1);